// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: fluentd.proto

package fluentd

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FluentdStartResponse_StartStatus int32

const (
	FluentdStartResponse_START_UNKNOWN  FluentdStartResponse_StartStatus = 0
	FluentdStartResponse_START_NOCHANGE FluentdStartResponse_StartStatus = 1
	FluentdStartResponse_START_SUCCESS  FluentdStartResponse_StartStatus = 2
	FluentdStartResponse_START_FAILED   FluentdStartResponse_StartStatus = 3
)

// Enum value maps for FluentdStartResponse_StartStatus.
var (
	FluentdStartResponse_StartStatus_name = map[int32]string{
		0: "START_UNKNOWN",
		1: "START_NOCHANGE",
		2: "START_SUCCESS",
		3: "START_FAILED",
	}
	FluentdStartResponse_StartStatus_value = map[string]int32{
		"START_UNKNOWN":  0,
		"START_NOCHANGE": 1,
		"START_SUCCESS":  2,
		"START_FAILED":   3,
	}
)

func (x FluentdStartResponse_StartStatus) Enum() *FluentdStartResponse_StartStatus {
	p := new(FluentdStartResponse_StartStatus)
	*p = x
	return p
}

func (x FluentdStartResponse_StartStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FluentdStartResponse_StartStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fluentd_proto_enumTypes[0].Descriptor()
}

func (FluentdStartResponse_StartStatus) Type() protoreflect.EnumType {
	return &file_fluentd_proto_enumTypes[0]
}

func (x FluentdStartResponse_StartStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FluentdStartResponse_StartStatus.Descriptor instead.
func (FluentdStartResponse_StartStatus) EnumDescriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{1, 0}
}

type FluentdStopResponse_StopStatus int32

const (
	FluentdStopResponse_STOP_UNKNOWN  FluentdStopResponse_StopStatus = 0
	FluentdStopResponse_STOP_NOCHANGE FluentdStopResponse_StopStatus = 1
	FluentdStopResponse_STOP_SUCCESS  FluentdStopResponse_StopStatus = 2
	FluentdStopResponse_STOP_FAILED   FluentdStopResponse_StopStatus = 3
)

// Enum value maps for FluentdStopResponse_StopStatus.
var (
	FluentdStopResponse_StopStatus_name = map[int32]string{
		0: "STOP_UNKNOWN",
		1: "STOP_NOCHANGE",
		2: "STOP_SUCCESS",
		3: "STOP_FAILED",
	}
	FluentdStopResponse_StopStatus_value = map[string]int32{
		"STOP_UNKNOWN":  0,
		"STOP_NOCHANGE": 1,
		"STOP_SUCCESS":  2,
		"STOP_FAILED":   3,
	}
)

func (x FluentdStopResponse_StopStatus) Enum() *FluentdStopResponse_StopStatus {
	p := new(FluentdStopResponse_StopStatus)
	*p = x
	return p
}

func (x FluentdStopResponse_StopStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FluentdStopResponse_StopStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fluentd_proto_enumTypes[1].Descriptor()
}

func (FluentdStopResponse_StopStatus) Type() protoreflect.EnumType {
	return &file_fluentd_proto_enumTypes[1]
}

func (x FluentdStopResponse_StopStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FluentdStopResponse_StopStatus.Descriptor instead.
func (FluentdStopResponse_StopStatus) EnumDescriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{3, 0}
}

type FluentdRestartResponse_RestartStatus int32

const (
	FluentdRestartResponse_RESTART_UNKNOWN        FluentdRestartResponse_RestartStatus = 0
	FluentdRestartResponse_RESTART_SUCCESS        FluentdRestartResponse_RestartStatus = 1
	FluentdRestartResponse_RESTART_FAILED_STARTED FluentdRestartResponse_RestartStatus = 2
	FluentdRestartResponse_RESTART_FAILED_STOPPED FluentdRestartResponse_RestartStatus = 3
)

// Enum value maps for FluentdRestartResponse_RestartStatus.
var (
	FluentdRestartResponse_RestartStatus_name = map[int32]string{
		0: "RESTART_UNKNOWN",
		1: "RESTART_SUCCESS",
		2: "RESTART_FAILED_STARTED",
		3: "RESTART_FAILED_STOPPED",
	}
	FluentdRestartResponse_RestartStatus_value = map[string]int32{
		"RESTART_UNKNOWN":        0,
		"RESTART_SUCCESS":        1,
		"RESTART_FAILED_STARTED": 2,
		"RESTART_FAILED_STOPPED": 3,
	}
)

func (x FluentdRestartResponse_RestartStatus) Enum() *FluentdRestartResponse_RestartStatus {
	p := new(FluentdRestartResponse_RestartStatus)
	*p = x
	return p
}

func (x FluentdRestartResponse_RestartStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FluentdRestartResponse_RestartStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fluentd_proto_enumTypes[2].Descriptor()
}

func (FluentdRestartResponse_RestartStatus) Type() protoreflect.EnumType {
	return &file_fluentd_proto_enumTypes[2]
}

func (x FluentdRestartResponse_RestartStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FluentdRestartResponse_RestartStatus.Descriptor instead.
func (FluentdRestartResponse_RestartStatus) EnumDescriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{5, 0}
}

type FluentdStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FluentdStartRequest) Reset() {
	*x = FluentdStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdStartRequest) ProtoMessage() {}

func (x *FluentdStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdStartRequest.ProtoReflect.Descriptor instead.
func (*FluentdStartRequest) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{0}
}

type FluentdStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status FluentdStartResponse_StartStatus `protobuf:"varint,1,opt,name=status,proto3,enum=fluentd.FluentdStartResponse_StartStatus" json:"status,omitempty"`
}

func (x *FluentdStartResponse) Reset() {
	*x = FluentdStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdStartResponse) ProtoMessage() {}

func (x *FluentdStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdStartResponse.ProtoReflect.Descriptor instead.
func (*FluentdStartResponse) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{1}
}

func (x *FluentdStartResponse) GetStatus() FluentdStartResponse_StartStatus {
	if x != nil {
		return x.Status
	}
	return FluentdStartResponse_START_UNKNOWN
}

type FluentdStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FluentdStopRequest) Reset() {
	*x = FluentdStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdStopRequest) ProtoMessage() {}

func (x *FluentdStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdStopRequest.ProtoReflect.Descriptor instead.
func (*FluentdStopRequest) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{2}
}

type FluentdStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status FluentdStopResponse_StopStatus `protobuf:"varint,1,opt,name=status,proto3,enum=fluentd.FluentdStopResponse_StopStatus" json:"status,omitempty"`
}

func (x *FluentdStopResponse) Reset() {
	*x = FluentdStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdStopResponse) ProtoMessage() {}

func (x *FluentdStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdStopResponse.ProtoReflect.Descriptor instead.
func (*FluentdStopResponse) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{3}
}

func (x *FluentdStopResponse) GetStatus() FluentdStopResponse_StopStatus {
	if x != nil {
		return x.Status
	}
	return FluentdStopResponse_STOP_UNKNOWN
}

type FluentdRestartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FluentdRestartRequest) Reset() {
	*x = FluentdRestartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdRestartRequest) ProtoMessage() {}

func (x *FluentdRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdRestartRequest.ProtoReflect.Descriptor instead.
func (*FluentdRestartRequest) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{4}
}

type FluentdRestartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status FluentdRestartResponse_RestartStatus `protobuf:"varint,1,opt,name=status,proto3,enum=fluentd.FluentdRestartResponse_RestartStatus" json:"status,omitempty"`
}

func (x *FluentdRestartResponse) Reset() {
	*x = FluentdRestartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdRestartResponse) ProtoMessage() {}

func (x *FluentdRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdRestartResponse.ProtoReflect.Descriptor instead.
func (*FluentdRestartResponse) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{5}
}

func (x *FluentdRestartResponse) GetStatus() FluentdRestartResponse_RestartStatus {
	if x != nil {
		return x.Status
	}
	return FluentdRestartResponse_RESTART_UNKNOWN
}

var File_fluentd_proto protoreflect.FileDescriptor

var file_fluentd_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x6c, 0x75, 0x65,
	0x6e, 0x74, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xb4, 0x01, 0x0a, 0x14, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e,
	0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x59, 0x0a, 0x0b, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x4e, 0x4f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74,
	0x64, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xac, 0x01, 0x0a,
	0x13, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x46,
	0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x54, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4e, 0x4f,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x4f, 0x50,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54,
	0x4f, 0x50, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x22, 0x17, 0x0a, 0x15, 0x46,
	0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xd2, 0x01, 0x0a, 0x16, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2d, 0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74,
	0x64, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x71, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x01, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a,
	0x16, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f,
	0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x32, 0xde, 0x01, 0x0a, 0x07, 0x46, 0x6c,
	0x75, 0x65, 0x6e, 0x74, 0x64, 0x12, 0x44, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1c,
	0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66,
	0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x53,
	0x74, 0x6f, 0x70, 0x12, 0x1b, 0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c,
	0x75, 0x65, 0x6e, 0x74, 0x64, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e,
	0x74, 0x64, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e, 0x2e, 0x66, 0x6c, 0x75, 0x65,
	0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x6c, 0x75, 0x65,
	0x6e, 0x74, 0x64, 0x2e, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fluentd_proto_rawDescOnce sync.Once
	file_fluentd_proto_rawDescData = file_fluentd_proto_rawDesc
)

func file_fluentd_proto_rawDescGZIP() []byte {
	file_fluentd_proto_rawDescOnce.Do(func() {
		file_fluentd_proto_rawDescData = protoimpl.X.CompressGZIP(file_fluentd_proto_rawDescData)
	})
	return file_fluentd_proto_rawDescData
}

var file_fluentd_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_fluentd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fluentd_proto_goTypes = []interface{}{
	(FluentdStartResponse_StartStatus)(0),     // 0: fluentd.FluentdStartResponse.StartStatus
	(FluentdStopResponse_StopStatus)(0),       // 1: fluentd.FluentdStopResponse.StopStatus
	(FluentdRestartResponse_RestartStatus)(0), // 2: fluentd.FluentdRestartResponse.RestartStatus
	(*FluentdStartRequest)(nil),               // 3: fluentd.FluentdStartRequest
	(*FluentdStartResponse)(nil),              // 4: fluentd.FluentdStartResponse
	(*FluentdStopRequest)(nil),                // 5: fluentd.FluentdStopRequest
	(*FluentdStopResponse)(nil),               // 6: fluentd.FluentdStopResponse
	(*FluentdRestartRequest)(nil),             // 7: fluentd.FluentdRestartRequest
	(*FluentdRestartResponse)(nil),            // 8: fluentd.FluentdRestartResponse
}
var file_fluentd_proto_depIdxs = []int32{
	0, // 0: fluentd.FluentdStartResponse.status:type_name -> fluentd.FluentdStartResponse.StartStatus
	1, // 1: fluentd.FluentdStopResponse.status:type_name -> fluentd.FluentdStopResponse.StopStatus
	2, // 2: fluentd.FluentdRestartResponse.status:type_name -> fluentd.FluentdRestartResponse.RestartStatus
	3, // 3: fluentd.Fluentd.Start:input_type -> fluentd.FluentdStartRequest
	5, // 4: fluentd.Fluentd.Stop:input_type -> fluentd.FluentdStopRequest
	7, // 5: fluentd.Fluentd.Restart:input_type -> fluentd.FluentdRestartRequest
	4, // 6: fluentd.Fluentd.Start:output_type -> fluentd.FluentdStartResponse
	6, // 7: fluentd.Fluentd.Stop:output_type -> fluentd.FluentdStopResponse
	8, // 8: fluentd.Fluentd.Restart:output_type -> fluentd.FluentdRestartResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fluentd_proto_init() }
func file_fluentd_proto_init() {
	if File_fluentd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fluentd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fluentd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fluentd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fluentd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fluentd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdRestartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fluentd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdRestartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fluentd_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fluentd_proto_goTypes,
		DependencyIndexes: file_fluentd_proto_depIdxs,
		EnumInfos:         file_fluentd_proto_enumTypes,
		MessageInfos:      file_fluentd_proto_msgTypes,
	}.Build()
	File_fluentd_proto = out.File
	file_fluentd_proto_rawDesc = nil
	file_fluentd_proto_goTypes = nil
	file_fluentd_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FluentdClient is the client API for Fluentd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FluentdClient interface {
	Start(ctx context.Context, in *FluentdStartRequest, opts ...grpc.CallOption) (*FluentdStartResponse, error)
	Stop(ctx context.Context, in *FluentdStopRequest, opts ...grpc.CallOption) (*FluentdStopResponse, error)
	Restart(ctx context.Context, in *FluentdRestartRequest, opts ...grpc.CallOption) (*FluentdRestartResponse, error)
}

type fluentdClient struct {
	cc grpc.ClientConnInterface
}

func NewFluentdClient(cc grpc.ClientConnInterface) FluentdClient {
	return &fluentdClient{cc}
}

func (c *fluentdClient) Start(ctx context.Context, in *FluentdStartRequest, opts ...grpc.CallOption) (*FluentdStartResponse, error) {
	out := new(FluentdStartResponse)
	err := c.cc.Invoke(ctx, "/fluentd.Fluentd/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluentdClient) Stop(ctx context.Context, in *FluentdStopRequest, opts ...grpc.CallOption) (*FluentdStopResponse, error) {
	out := new(FluentdStopResponse)
	err := c.cc.Invoke(ctx, "/fluentd.Fluentd/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluentdClient) Restart(ctx context.Context, in *FluentdRestartRequest, opts ...grpc.CallOption) (*FluentdRestartResponse, error) {
	out := new(FluentdRestartResponse)
	err := c.cc.Invoke(ctx, "/fluentd.Fluentd/Restart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FluentdServer is the server API for Fluentd service.
type FluentdServer interface {
	Start(context.Context, *FluentdStartRequest) (*FluentdStartResponse, error)
	Stop(context.Context, *FluentdStopRequest) (*FluentdStopResponse, error)
	Restart(context.Context, *FluentdRestartRequest) (*FluentdRestartResponse, error)
}

// UnimplementedFluentdServer can be embedded to have forward compatible implementations.
type UnimplementedFluentdServer struct {
}

func (*UnimplementedFluentdServer) Start(context.Context, *FluentdStartRequest) (*FluentdStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedFluentdServer) Stop(context.Context, *FluentdStopRequest) (*FluentdStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedFluentdServer) Restart(context.Context, *FluentdRestartRequest) (*FluentdRestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}

func RegisterFluentdServer(s *grpc.Server, srv FluentdServer) {
	s.RegisterService(&_Fluentd_serviceDesc, srv)
}

func _Fluentd_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FluentdStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluentdServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fluentd.Fluentd/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluentdServer).Start(ctx, req.(*FluentdStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fluentd_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FluentdStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluentdServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fluentd.Fluentd/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluentdServer).Stop(ctx, req.(*FluentdStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fluentd_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FluentdRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluentdServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fluentd.Fluentd/Restart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluentdServer).Restart(ctx, req.(*FluentdRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fluentd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fluentd.Fluentd",
	HandlerType: (*FluentdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Fluentd_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Fluentd_Stop_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Fluentd_Restart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fluentd.proto",
}
